# docker-compose.yml
libopenscap8: 
    build: .
    command: rake build publish PUBLISH_DIR=/data/pkg/xenial --trace
    volumes: 
        - .:/data
    working_dir: /data
    stdin_open: true
    tty: true
